# Generated by Django 3.0 on 2023-03-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('apeliidos', models.CharField(max_length=220)),
                ('nacionaldad', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
